version: '3.5'
services:
  database-service:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cake -d cake || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    image: postgres:10
    container_name: database-container
    environment:
    - POSTGRES_PASSWORD=senhacake
    - POSTGRES_USER=cake
    - POSTGRES_DB=cake
    - POSTGRES_DB_TEST=cake-test
    ports:
    - "5433:5432"
    expose:
    - "5432"
    volumes:
    - ./database/docker-data/postgres:/var/lib/postgresql/data
    - ./database/:/docker-entrypoint-initdb.d/
    networks:
    - cake_network
  webapp-service:
    #    build: ./webapp
    build: webapp/.
    image: vinnyfs89/docker-cakephp2x
    container_name: webapp-container
    volumes:
    - ./webapp:/var/www/html
#    ports:
#    - "8080:8080"
    environment:
    - NODE_ENV=development
    networks:
    - cake_network
    links:
      - database-service:db
# docker network create cake_network

networks:
  cake_network:
    name: cake_network
    driver: bridge
